document.addEventListener('DOMContentLoaded', () => {
    // --- DATABASE OF QUESTIONS (NOMOR SUDAH URUT) ---
    const surveyQuestions = [
        { id: 1, type: 'radio', question: "Apakah kamu perempuan atau laki-laki?", options: ["Perempuan", "Laki-laki"], category: 'demographics' },
        { id: 2, type: 'radio', question: "Ada berapa keluarga yang tinggal bersama di rumahmu?", options: ["Hanya keluarga intiku sendiri (orang tua dan saudara kandungku saja).", "Keluargaku bersama satu keluarga lain.", "Keluargaku bersama dua keluarga lain.", "Keluargaku bersama tiga atau lebih keluarga lain."], category: 'demographics' },
        { id: 3, type: 'radio', question: "Apa jenjang sekolah tertinggi yang diselesaikan ibumu?", options: ["SD", "SMP", "SMA/SMK", "Diploma (D1, D2 atau D3)", "Sarjana (S1)", "Master (S2)", "Doktor (S3)", "Tidak tahu"], category: 'demographics' },
        { id: 4, type: 'radio', question: "Apa pekerjaan ayahmu?", options: ["Tidak bekerja", "Pensiunan", "Anggota militer/polisi", "Perwira militer/polisi", "Buruh/Karyawan kecil", "Bekerja mandiri/Wiraswasta kecil", "Tenaga pemasaran", "Pekerja administratif", "Manajer/Pimpinan", "Profesional", "Pejabat/Legislatif", "Pemilik usaha kecil", "Pemilik perusahaan besar", "Tidak tahu"], category: 'demographics' },
        { id: 5, type: 'radio', question: "Apa pekerjaan ibumu?", options: ["Tidak bekerja", "Pensiunan", "Anggota militer/polisi", "Perwira militer/polisi", "Buruh/Karyawan kecil", "Bekerja mandiri/Wiraswasta kecil", "Tenaga pemasaran", "Pekerja administratif", "Manajer/Pimpinan", "Profesional", "Pejabat/Legislatif", "Pemilik usaha kecil", "Pemilik perusahaan besar", "Tidak tahu"], category: 'demographics' },
        { id: 6, type: 'matrix', question: "Adakah barang-barang berikut di rumahmu?", rows: ["Meja belajar", "Kamar tidur untuk dirimu sendiri", "Tempat belajar yang tenang", "Listrik dan lampu untuk belajar di malam hari", "Komputer, laptop, atau tablet", "Perangkat lunak pendidikan", "Sambungan ke internet", "Alat baca buku digital"], columns: ["Tidak ada", "Ada"], category: 'home_resource' },
        { id: 7, type: 'matrix', question: "Berapa jumlah buku-buku yang ada di rumahmu?", rows: ["Buku fiksi/sastra", "Buku sains/teknologi", "Buku seni/musik/desain", "Buku bahasa/kamus", "Buku penunjang tugas sekolah"], columns: ["Tidak ada", "Kira-kira 1-10 buku", "Kira-kira 11-25 buku", "Kira-kira 26-100 buku", "Kira-kira lebih dari 100 buku"], category: 'home_resource' },
        { id: 8, type: 'matrix', question: "Dalam kegiatan pembelajaran, apakah hal berikut terjadi di kelasmu?", rows: ["Guru memberi kesempatan berdiskusi", "Guru masuk kelas tepat waktu", "Peralatan kelas tertata rapih", "Guru memonitor kemajuan tugas rutin", "Guru mengingatkan tenggat waktu & sanksi", "Guru memberikan penghargaan tugas baik"], columns: ["Tidak Pernah", "Jarang", "Sering", "Sangat sering"], category: 'teaching_quality' },
        { id: 9, type: 'matrix', question: "Selama satu tahun terakhir ini, seberapa sering kamu mengalami hal berikut di kelas?", rows: ["Bisa mengerjakan tugas karena instruksi jelas", "Kelas dimulai dan diakhiri tepat waktu", "Siswa dilibatkan menyusun aturan kelas", "Guru konsisten menegakkan aturan"], columns: ["Tidak pernah atau sangat jarang", "Di beberapa pelajaran", "Di sebagian besar pelajaran", "Di semua pelajaran"], category: 'teaching_quality' },
        { id: 10, type: 'matrix', question: "Dalam kegiatan pembelajaran, apakah hal berikut terjadi di kelasmu?", rows: ["Mendapatkan bantuan khusus dari guru", "Mendapatkan penjelasan ulang jika tidak mengerti"], columns: ["Tidak pernah atau sangat jarang", "Di beberapa pelajaran", "Di sebagian besar pelajaran", "Di semua pelajaran"], category: 'teaching_quality' },
        { id: 11, type: 'matrix', question: "Dalam kegiatan pembelajaran, apakah hal berikut terjadi di kelasmu?", rows: ["Diberi tugas yang menantang", "Guru mendorong untuk meningkatkan kemampuan"], columns: ["Tidak Pernah", "Jarang", "Sering", "Sangat sering"], category: 'teaching_quality' },
        { id: 12, type: 'matrix', question: "Selama satu tahun terakhir ini, apakah kamu mendapatkan hal berikut dari guru?", rows: ["Menerima hasil ujian yang sudah dinilai", "Mendapatkan komentar tertulis tentang tugas", "Mendapatkan saran perbaikan tugas"], columns: ["Tidak ada satu pun guru", "Ya, sebagian kecil guru", "Ya, sebagian besar guru", "Ya, semua guru"], category: 'teaching_quality' },
        { id: 13, type: 'matrix', question: "Selama satu tahun terakhir ini, seberapa sering kamu mengalami hal berikut di kelas?", rows: ["Merasa tertekan hingga mencontek/curang", "Guru tidak membiarkanmu menyerah", "Guru percaya kamu mampu", "Guru menanyakan kabar sebelum kelas", "Guru merespon keluhan siswa", "Guru memberi komentar agar lebih mengerti", "Guru memberi komentar agar lebih percaya diri"], columns: ["Tidak pernah atau sangat jarang", "Di beberapa pelajaran", "Di sebagian besar pelajaran", "Di semua pelajaran"], category: 'student_wellbeing' },
